In [1]:
'''
@Author: Haihui Pan
@Date: 2021-12-04
@Ref: https://numpy.org/doc/stable/
'''
import numpy as np

## 索引&切片

* 同List一样，numpy数组可以通过索引和切片来进行访问和修改。索引是指通过指定下标来获取目标元素，切片则是通过从原数组中切割出一个新数组。

In [2]:
#单值索引
np_a=np.arange(0,10)

print(np_a)

#取第2个元素
print('第2个元素:',np_a[1])

#取最后一个元素
print("最后一个元素:",np_a[-1])

[0 1 2 3 4 5 6 7 8 9]
第2个元素: 1
最后一个元素: 9


* Numpy的切片可以通过冒号分隔切片参数 ***start:stop:step***来切片 
* 切片还可以使用'...'来对应维度上的所有对象

In [3]:
# [0 1 2 3 4 5 6 7 8 9]
np_a=np.arange(0,10)

#按照间隔取值
np_slice=np_a[0:10:2]
print(np_slice)

[0 2 4 6 8]


In [4]:
np_a=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
#取第一列
print(np_a[...,0]) #...相当于取[1,2,3],[4,5,6],[7,8,9]；0表示取index=0的元素

#取第2,3列所有元素
print(np_a[...,1:])

[1 4 7]
[[2 3]
 [5 6]
 [8 9]]


## 高级索引
* 布尔索引:通过布尔运算来获取符合指定条件的元素的数组
* 条件索引:np.where函数用于返回满足条件的元素索引，也可以达到布尔索引的效果
* 花式索引:利用整数数组进行索引,与切片不同的是，它总是将数据复制到新数组中

### 布尔索引

In [5]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

#输出大于3的数
print(a[a>3])

[4 5 6 7 8 9]


In [6]:
a=np.array([1,2,3,np.nan,3,4])

#输出数组中非空元素
print(a[~np.isnan(a)]) 

[1. 2. 3. 3. 4.]


### 条件索引

In [7]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

#大于3的元素索引
np_index=np.where(a>3)
print(np_index)

#输出满足条件元素
print(a[np_index])

(array([1, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 2], dtype=int64))
[4 5 6 7 8 9]


In [8]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

#数组中为偶数的元素索引
np_index=np.where(a%2==0)
print(np_index)

#输出满足条件元素
print(a[np_index])

(array([0, 1, 1, 2], dtype=int64), array([1, 0, 2, 1], dtype=int64))
[2 4 6 8]


### 花式索引

In [9]:
#花式索引，取指定位置的多个对象
a=np.array([[0,0],
            [1,1],
            [2,2]])

#取a[2],a[0]
print(a[[2,0]])

[[2 2]
 [0 0]]


## 排序

* np.sort(a, axis, kind, order) 函数返回输入数组的排序副本
  * a: 待排序的数组
  * axis: 排序数组的轴；默认值为-1
  * kind: 排序算法；默认为quicksort
  * order: 若数组包含字段，则为排序的字段

In [10]:
x=np.array([[4,3,5],
            [9,2,3]])

#axis=-1,表示对x[0][:],x[1][:]的元素进行排序
print(np.sort(x))

[[3 4 5]
 [2 3 9]]


In [11]:
x=np.array([[4,3,5],
            [9,2,3]])

#axis=0，则按照列来进行排序; x[:][0],x[:][1],x[:][2]来进行排序
print(np.sort(x,axis=0))

[[4 2 3]
 [9 3 5]]


In [12]:
# S20：表示数据类型为字符串，每个字符串字节长度为20的意思
dt=np.dtype([('name','S20'),('age',np.int)])

np_student=np.array([('Tom',12),('Mike',8),('Marry',10)],dtype=dt)
print(np.sort(np_student,order='age'))

[(b'Mike',  8) (b'Marry', 10) (b'Tom', 12)]
