In [1]:
'''
@Author: Haihui Pan
@Date: 2021-12-05
@Ref:
[0]https://numpy.org/doc/stable/
[1]https://www.runoob.com/numpy/numpy-tutorial.html
'''

import numpy as np

## 统计函数
* 最值(最大，最小，对应的index)
* 均值，方差，标准差
* 分位数，中位数，极差

### 取最值

* np.min(a, axis):用于计算沿指定轴的最小值
* np.argmin(a, axis):用于计算沿指定轴的最小值元素的索引
* np.max(a, axis):用于计算沿指定轴的最大值
* np.argmax(a, axis):用于计算沿指定轴的最大值元素的索引

In [2]:
# np.amin(a, axis)用于计算沿指定轴的最小值
x=np.array([[2,3,4],
            [1,8,3],
            [5,7,0]])

#默认是全部元素的最小值
print(np.min(x),'index:',np.argmin(x))

#指定轴的最小值 axis=0，则为x[0],x[1],x[2]同位置比大小，相当于列
print(np.min(x,axis=0),'index:',np.argmin(x,axis=0))

#axis=1，则为min(a[0][i]),min(a[1][i]),min(a[2][i]),相当于行
print(np.min(x,axis=1),'index:',np.argmin(x,axis=1))

0 index: 8
[1 3 0] index: [1 0 2]
[2 1 0] index: [0 0 2]


In [3]:
# np.max(a, axis)用于计算沿指定轴的最大值
x=np.array([[2,3,4],
            [1,8,3],
            [5,7,0]])

#默认是全部元素的最大值（相当于将数组拉平）
print(np.max(x),'index:',np.argmax(x))

#axis=0，则为x[0],x[1],x[2]同位置比大小，相当于列
print(np.max(x,axis=0),'index:',np.argmax(x,axis=0))

#axis=1，则为max(a[0][i]),max(a[1][i]),max(a[2][i]),相当于行
print(np.max(x,axis=1),'index:',np.argmax(x,axis=1))

8 index: 4
[5 8 4] index: [2 1 0]
[4 8 7] index: [2 1 1]


### 均值，方差，标准差

In [4]:
x=np.arange(10)

#均值
x_mean=np.mean(x)

#方差
x_var=np.var(x)

#标准差
x_std=np.std(x)

print(x)
print('mean:',x_mean, 'var:',x_var, 'std:',x_std)

[0 1 2 3 4 5 6 7 8 9]
mean: 4.5 var: 8.25 std: 2.8722813232690143


### 中位数，分位数和极差

In [5]:
x=np.arange(10)

#中位数
print('median:',np.median(x))

#计算指定50%分位数(即为中位数)
print(np.percentile(x, 50))

#计算75%分位数
print(np.percentile(x,75))

#极差
print('max-min:',np.ptp(x))

median: 4.5
4.5
6.75
max-min: 9


## 线性代数

### 点积

* 点击(dot):表示矩阵内积，当数组为二维时，则为矩阵积

In [6]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[11,12],
              [13,14]])

c=np.dot(a,b)
print(c)

[[37 40]
 [85 92]]


In [7]:
a = np.array([1,2,3])
b = np.array([1,2,3])

c=np.dot(a,b)
print(c)

14


### 元素积(element-wise product)

* 两个数组相同位置上的元素进行相乘

In [8]:
a = np.array([1,2,3])
b = np.array([1,2,3])

c=a*b
print(c)

[1 4 9]


### 内积

In [9]:
a=np.array([1,2,3])
b=np.array([1,2,3])

c=np.inner(a,b)
print(c)

14


### 矩阵乘法

In [10]:
a=np.array([[0,1],
            [2,3]])
b=np.array([[1,4],
            [2,1]])

c=np.matmul(a,b)
print(c)

[[ 2  1]
 [ 8 11]]


### 行列式

In [11]:
x=np.array([[2,1],
             [1,8]])

x_det=np.linalg.det(x)
print(x_det)

15.0


### 逆矩阵&线性方程解

线性方程组：<br>
x + y + z = 6<br>
2y + 5z = -4<br>
2x + 5y - z = 27<br>

可以使用线性代数的求解为:<br>
$Ax=y \longrightarrow  x=A^{-1}y$

In [12]:
%%html 
<img src="np_02.png",width="40%",height="40%">

In [13]:
A = np.array([[1,1,1],
              [0,2,5],
              [2,5,-1]])

#求逆矩阵
A_inv=np.linalg.inv(A)

#矩阵y
y=np.array([[6],[-4],[27]])

#解方程
x=np.dot(A_inv,y)
print(x)

[[ 5.]
 [ 3.]
 [-2.]]
