In [1]:
'''
@Author: Haihui Pan
@Date: 2021-12-05
@Ref:
[0]https://numpy.org/doc/stable/
[1]https://www.runoob.com/numpy/numpy-tutorial.html
'''
import numpy as np

## 广播(Broadcast)

* 广播(Broadcast)是Numpy针对不同shape的数组进行数值计算的方式。
   * 若数组a.shape==b.shape，则a,b对应位置元素进行操作
   * 若数组a.shape!=b.shape, 则触发广播机制会进行自动补齐

In [2]:
a=np.array([1,2,3,4])
b=np.array([1,])

#由于b的shape不够，会自动将b广播为[1,1,1,1]
print(a+b)

[2 3 4 5]


In [3]:
#对于高维也一样
a=np.array([[1,1,1],
            [2,2,2]])
b=np.array([1,1,1])

#会自动广播b
print(a+b)

[[2 2 2]
 [3 3 3]]


## 数组操作

### 修改形状

In [4]:
a=np.arange(10)

#shape变为2*5
a=a.reshape((2,5))
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### 对换维度

In [5]:
a=np.arange(10)

#先reshape为2*5
a=a.reshape((2,5))

#对换数轴，变为5*2
a=np.transpose(a,[1,0])
print(a)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


### 修改维度

In [6]:
#扩充维度 
a=np.arange(3)

#通过在指定位置插入新的轴 [0,1,2]->[[0],[1],[2]],
a=np.expand_dims(a,axis=1)
print(a)

[[0]
 [1]
 [2]]


In [7]:
#降低维度，主要用于去除一些无用的轴

# shape:1*2*2
a=np.array([[[1,2],[3,4]]])
print(a.shape)

#去掉第一维度的轴为2*2
a=np.squeeze(a,axis=0)
print(a.shape)

(1, 2, 2)
(2, 2)


### 数组拼接
* np.concatenate((a1, a2, ...), axis)
  * (a1, a2, ...):待拼接的数组
  * axis:拼接数组的轴维度
* np.hstack:按照水平方向来堆叠生成数组
* np.vstack:按照垂直方向来堆叠生成数组

In [8]:
# 按照指定维度拼接数组
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

#按照axis=0来进行拼接，即为[a[0],a[1],b[0],b[1]]
c=np.concatenate((a,b),axis=0)
print(c)

#按照axis=1来进行拼接,即为[a[0]b[0],a[1]b[1]]
d=np.concatenate((a,b),axis=1)
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [9]:
# np.hstack相当于按行来进行拼接
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])

c=np.hstack((a,b))
print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [10]:
#np.vatsck相当于按列来进行
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])

c=np.vstack((a,b))
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## 内置数学函数

### 三角函数

In [11]:
x=np.array([1,2,3,4])

print(np.sin(x))
print(np.cos(x))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


### 取整函数 

In [12]:
#向上取整
x=np.array([1.1, 2.3, 9.8])

x=np.ceil(x)
print(x)

[ 2.  3. 10.]


In [13]:
#向下取整
x=np.array([1.1, 2.3, 9.8])

x=np.floor(x)
print(x)

[1. 2. 9.]


### 舍入函数

* np.around(a,decimals)
  * a:数组
  * decimals:四舍五入的小数点

In [14]:
x=np.array([1.235,-0.987,7.666])

#保留2位小数
x=np.around(x,decimals=2)
print(x)

[ 1.24 -0.99  7.67]
